[package]
name = "web"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.3.0"
tokio = { version = "0", features = ["rt-util"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0"
rand = "0"